#taken from https://github.com/google-deepmind/alphafold3/blob/20ad0a21eb49febcaad4a6f5d71aa6b701512e5b/src/alphafold3/constants/residue_names.py

CCD_NAME_TO_ONE_LETTER = {k: v for k, v in {
    '00C': 'C', '0AA': 'V', '0AB': 'V',
    '0AC': 'G', '0AD': 'G', '0AG': 'L', '0AH': 'S', '0AK': 'D',
    '0AM': 'A', '0CS': 'A', '0FL': 'A',
    '0NC': 'A', '0SP': 'A', 'ABA': 'A', 'ABR': 'A',
    'ABS': 'A', 'ACB': 'D', 'AET': 'A', 'AHO': 'A',
    'AHP': 'A', 'AIB': 'A', 'AKL': 'D', 'AKZ': 'D',
    'ALA': 'A', 'ALC': 'A', 'ALM': 'A', 'ALN': 'A',
    'ALS': 'A', 'ALT': 'A', 'ALV': 'A', 'ALY': 'K',
    'APH': 'A', 'API': 'K', 'APK': 'K',
    'AR2': 'R', 'AR4': 'E', 'AR7': 'R', 'ARG': 'R', 'ARM': 'R', 'ARO': 'R',
    'AS2': 'D', 'ASA': 'D', 'ASB': 'D',
    'ASI': 'D', 'ASK': 'D', 'ASL': 'D', 'ASN': 'N', 'ASP': 'D',
    'ASQ': 'D', 'AYA': 'A', 'AZK': 'K', 'AZS': 'S',
    'B2A': 'A', 'B2V': 'V',
    'B3A': 'A', 'B3D': 'D', 'B3E': 'E', 'B3K': 'K',
    'B3S': 'S', 'BFD': 'D', 'BG1': 'S',
    'BHD': 'D', 'BLE': 'L', 'BLY': 'K',
    'BOR': 'R', 'BTA': 'L', 'BUG': 'V',
    'C25': 'C', 'C2L': 'C', 'C2S': 'C', 'C31': 'C', 'C32': 'C',
    'C34': 'C', 'C36': 'C', 'C37': 'C', 'C38': 'C', 'C3Y': 'C',
    'C42': 'C', 'C43': 'C', 'C45': 'C', 'C46': 'C', 'C49': 'C',
    'C4R': 'C', 'C4S': 'C', 'C5C': 'C', 'C6C': 'C', 'CAF': 'C',
    'CAR': 'C', 'CAY': 'C', 'CB2': 'C', 'CBR': 'C', 'CBV': 'C',
    'CCS': 'C', 'CDW': 'C', 'CEA': 'C', 'CFL': 'C',
    'CME': 'C', 'CMH': 'C', 'CML': 'C', 'CMR': 'C', 'CMT': 'C',
    'CS0': 'C', 'CS1': 'C', 'CS3': 'C', 'CS4': 'C',
    'CSA': 'C', 'CSB': 'C', 'CSD': 'C', 'CSE': 'C', 'CSF': 'C',
    'CSJ': 'C', 'CSL': 'C', 'CSO': 'C', 'CSP': 'C', 'CSR': 'C',
    'CSS': 'C', 'CSU': 'C', 'CSW': 'C', 'CSX': 'C', 'CSZ': 'C',
    'CY0': 'C', 'CY1': 'C', 'CY3': 'C', 'CY4': 'C', 'CYA': 'C',
    'CYD': 'C', 'CYF': 'C', 'CYG': 'C',
    'CYM': 'C', 'CYQ': 'C', 'CYR': 'C', 'CYS': 'C', 'CZ2': 'C',
    'CZZ': 'C', 'DAB': 'A', 'DAH': 'F', 'DAL': 'A',
    'DAR': 'R', 'DAS': 'D', 'DBY': 'Y', 'DBZ': 'A',
    'DCY': 'C', 'DGL': 'E', 'DGN': 'Q', 'DHI': 'H',
    'DHN': 'V', 'DHV': 'V', 'DI': 'I', 'DIL': 'I',
    'DIR': 'R', 'DIV': 'V', 'DLE': 'L', 'DLS': 'K',
    'DLY': 'K', 'DNE': 'L', 'DNG': 'L',
    'DNM': 'L', 'DPH': 'F', 'DPL': 'P', 'DPN': 'F',
    'DPR': 'P', 'DSE': 'S', 'DSN': 'S',
    'DSP': 'D', 'DTH': 'T', 'DTR': 'W', 'DTY': 'Y',
    'DVA': 'V', 'EFC': 'C', 'EHP': 'F',
    'ESB': 'Y', 'ESC': 'M', 'FCL': 'F',
    'FGL': 'G', 'FGP': 'S', 'FHL': 'L',
    'FLE': 'L', 'FLT': 'Y', 'FME': 'M',
    'FMG': 'G', 'FPA': 'F', 'FTR': 'W',
    'FTY': 'Y', 'FVA': 'V', 'GGL': 'E',
    'GHP': 'G', 'GLH': 'Q', 'GLJ': 'E',
    'GLK': 'E', 'GLN': 'Q', 'GLQ': 'E',
    'GLU': 'E', 'GLY': 'G', 'GLZ': 'G',
    'GMA': 'E', 'GMS': 'G', 'GSC': 'G',
    'GSR': 'G', 'GSS': 'G', 'GSU': 'E',
    'HAC': 'A', 'HAR': 'R', 'HHI': 'H',
    'HIA': 'H', 'HIC': 'H', 'HIP': 'H',
    'HIQ': 'H', 'HIS': 'H', 'HL2': 'L',
    'HLU': 'L', 'HMR': 'R', 'HPC': 'F',
    'HPE': 'F', 'HPH': 'F', 'HPQ': 'F',
    'HRP': 'W', 'HSE': 'S', 'HSL': 'S',
    'HSO': 'H', 'HTR': 'W', 'HVA': 'V',
    'HYP': 'P', 'IAM': 'A', 'IAR': 'R',
    'IAS': 'D', 'IEL': 'K', 'IGL': 'G',
    'IIL': 'I', 'ILE': 'I', 'ILG': 'E',
    'ILX': 'I', 'IML': 'I', 'IOY': 'F',
    'IPG': 'G', 'IYR': 'Y', 'KCX': 'K',
    'KGC': 'K', 'KOR': 'M', 'KPI': 'K',
    'KST': 'K', 'KYQ': 'K', 'LA2': 'K',
    'LAA': 'D', 'LAL': 'A', 'LBY': 'K',
    'LCK': 'K', 'LCX': 'K', 'LDH': 'K',
    'LED': 'L', 'LEF': 'L', 'LEH': 'L',
    'LEI': 'V', 'LEM': 'L', 'LEN': 'L',
    'LEU': 'L', 'LEX': 'L', 'LLP': 'K',
    'LLY': 'K', 'LME': 'E', 'LMF': 'K',
    'LMQ': 'Q', 'LPD': 'P', 'LPG': 'G',
    'LPS': 'S', 'LTR': 'W', 'LVG': 'G',
    'LVN': 'V', 'LYF': 'K', 'LYK': 'K',
    'LYM': 'K', 'LYN': 'K', 'LYR': 'K',
    'LYS': 'K', 'LYZ': 'K', 'M2L': 'K',
    'M2S': 'M', 'M3L': 'K', 'MAA': 'A',
    'MAI': 'R', 'MBQ': 'Y', 'MCL': 'K',
    'MCS': 'C', 'MCY': 'C', 'MEA': 'F',
    'MED': 'M', 'MEG': 'E', 'MEN': 'N',
    'MEQ': 'Q', 'MET': 'M', 'MEU': 'G',
    'MHO': 'M', 'MHS': 'H', 'MIS': 'S',
    'MK8': 'L', 'ML3': 'K', 'MLE': 'L',
    'MLL': 'L', 'MLY': 'K', 'MLZ': 'K',
    'MME': 'M', 'MNL': 'L', 'MNV': 'V',
    'MSE': 'M', 'MSL': 'M', 'MSO': 'M',
    'MTY': 'Y', 'MVA': 'V', 'NAL': 'A',
    'NAM': 'A', 'NBQ': 'Y', 'NC1': 'S',
    'NCB': 'A', 'NEP': 'H', 'NFA': 'F',
    'NHL': 'E', 'NIY': 'Y', 'NLE': 'L',
    'NLN': 'L', 'NLO': 'L', 'NLP': 'L',
    'NLQ': 'Q', 'NMM': 'R', 'NPH': 'C',
    'NPI': 'A', 'NTY': 'Y', 'NVA': 'V',
    'NYC': 'C', 'NYS': 'C', 'NZH': 'H',
    'OAS': 'S', 'OHS': 'D', 'OLT': 'T',
    'OMT': 'M', 'OPR': 'R', 'PAQ': 'Y',
    'PAS': 'D', 'PBB': 'C', 'PBF': 'F',
    'PCA': 'E', 'PCS': 'F', 'PEC': 'C',
    'PF5': 'F', 'PFF': 'F', 'PG1': 'S',
    'PGY': 'G', 'PHA': 'F', 'PHD': 'D',
    'PHE': 'F', 'PHI': 'F', 'PHL': 'F',
    'PHM': 'F', 'PLE': 'L', 'PM3': 'F',
    'PMT': 'C', 'POM': 'P', 'PPN': 'F',
    'PR3': 'C', 'PRN': 'A', 'PRO': 'P',
    'PRS': 'P', 'PSA': 'F', 'PSH': 'H',
    'PST': 'T', 'PSW': 'C', 'PTH': 'Y',
    'PTM': 'Y', 'PTR': 'Y', 'PVH': 'H',
    'PYA': 'A', 'PYX': 'C', 'QPA': 'C',
    'QPH': 'F', 'R1A': 'C', 'RC7': 'A',
    'RIA': 'A', 'SAC': 'S', 'SAH': 'C',
    'SAR': 'G', 'SBL': 'S', 'SC': 'C',
    'SCH': 'C', 'SCS': 'C', 'SCY': 'C',
    'SEB': 'S', 'SEL': 'S', 'SEM': 'S',
    'SEN': 'S', 'SEP': 'S', 'SER': 'S',
    'SET': 'S', 'SGB': 'S', 'SHC': 'C',
    'SHP': 'G', 'SHR': 'K', 'SIB': 'C',
    'SLA': 'P', 'SLR': 'P', 'SLZ': 'K',
    'SMC': 'C', 'SME': 'M', 'SMF': 'F',
    'SMP': 'A', 'SMT': 'T', 'SNC': 'C',
    'SOC': 'C', 'SOY': 'S', 'SPT': 'T',
    'SRA': 'A', 'STY': 'Y', 'SVA': 'S',
    'SVV': 'S', 'SVW': 'S', 'SVX': 'S',
    'SVY': 'S', 'SYS': 'C', 'T11': 'F',
    'TBM': 'T', 'TCQ': 'Y', 'TCR': 'W',
    'TCY': 'A', 'TDD': 'L', 'TFE': 'T',
    'TFQ': 'F', 'TH6': 'T', 'THC': 'T',
    'THR': 'T', 'TIH': 'A', 'TMB': 'T',
    'TMD': 'T', 'TNB': 'C', 'TOX': 'W',
    'TPL': 'W', 'TPO': 'T', 'TPQ': 'Y',
    'TQI': 'W', 'TQQ': 'W', 'TRF': 'W',
    'TRG': 'K', 'TRN': 'W', 'TRO': 'W',
    'TRP': 'W', 'TRQ': 'W', 'TRW': 'W',
    'TRX': 'W', 'TTY': 'Y', 'TY2': 'Y',
    'TY3': 'Y', 'TYB': 'Y', 'TYI': 'Y',
    'TYN': 'Y', 'TYO': 'Y', 'TYQ': 'Y',
    'TYR': 'Y', 'TYS': 'Y', 'TYY': 'Y',
    'VAD': 'V', 'VAF': 'V', 'VAL': 'V',
    'VDL': 'V', 'VLL': 'V', 'VME': 'V',
    'YCM': 'C', 'YOF': 'Y'
}.items() if v in ['A', 'R', 'N', 'D', 'C', 'Q', 'E', 'G', 'H', 'I', 'L', 'K', 'M', 'F', 'P', 'S', 'T', 'W', 'Y', 'V']}

